version: "2"
services:
    bot:
        image: odanado/os-command-injection:bot
        build: .
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/localtime:/etc/localtime:ro
        environment:
            - SLACK_TOKEN=$SLACK_TOKEN
        restart: always

    base:
        image: odanado/os-command-injection:base
        build:
            context: .
            dockerfile: Dockerfile.base

    bash:
        image: odanado/os-command-injection:bash
        build: langs/bash

    python2:
        image: odanado/os-command-injection:python2
        build: langs/python2

    python3:
        image: odanado/os-command-injection:python3
        build: langs/python3

    c:
        image: odanado/os-command-injection:c
        build: langs/c

    brainfuck:
        image: odanado/os-command-injection:brainfuck
        build: langs/brainfuck
    
    charp-shell:
        image: odanado/os-command-injection:csharp-shell
        build: langs/csharp-shell
